### PR TITLE
Render correct markdown for syntax highlight specification. 

### PR DESCRIPTION
**Pull request by alkemann**
NB! Initial state of this Pull Request is NOT WORKING, but made at library authors request.

### CODE REVIEW

**Comment by RobWin** [comment]
Thx.
I think you have to change `test.md` as well, so that two tests don't fail.

**Comment by alkemann** [comment]
I did change test.md?

**Comment by RobWin** [comment]
Strange. Two tests still fail:

**Comment by RobWin** [comment]
Strange. Two tests still fail.

MarkupDocBuilderTest > testMarkdownCodeBlock FAILED
MarkupDocBuilderTest > testMarkdown FAILED

**Comment by alkemann** [comment]
Yes. Like I said in the issue thread, I have been unable to successfully fix this and get the tests to past.

**Comment by cascer1** [comment]
I have used your modifications as a base for PR #28

**Comment by alkemann** [comment]
Since #28 is a working fix for this issue (confirmed with local build), I am closing this

**Pull request closed without merging**
